apiVersion: v1
kind: Pod
metadata:
  name: devops-01
  labels:
    app: devops-01
spec:
  containers:
  - name: devops-01
    image: floryos/devops-01:v001
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
      requests:
        memory: "32Mi"
        cpu: "100m"
      port:
        containerPort: 80
        protocol: TCP